apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - solr
  - dataverse

images:
  - name: steinsteiny/dataverse:5.4.1
    newTag: "5.4.1"
  - name: iqss/solr-k8s
    newTag: "5.4.1"
