apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - solr
  - dataverse

images:
  - name: steinsteiny/dataverse
    newTag: "5.4.1"
  - name: steinsteiny/solr-k8s
    newTag: "7-5.4.1"
