---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dataverse
  labels:
    app.kubernetes.io/name: configmap
    app.kubernetes.io/part-of: dataverse
data:
  db_DoiProvider: FAKE
  db_SystemEmail: "Dataverse-SSHOC <info@dataverse.cessda.eu>"

  ### CUSTOMIZATION
  db_StatusMessageHeader: "This Dataverse instance is for testing only." 
  db_StatusMessageText: "Any data or metadata added is subject to unforewarned destruction."
  db_FooterCopyright: " - Social Sciences & Humanities Open Cloud (SSHOC)"
  db_NavbarAboutUrl: "https://sshopencloud.eu"

  
